name    'kickstandproject-timezone'
version '0.0.4'
author 'kickstandproject'
license 'Apache 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'https://github.com/kickstandproject/kickstandproject-timezone'
